### ISSUE TITLE
Improve UX for lockfile generation from manifests

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/cli#1076]
# Overview
The `lockfile_generator` crate is used to generate a lockfile from a manifest when there is no lockfile available. This crate makes assumptions about the tools (and their versions) that are available on the `PATH` for generation activities. However, it is possible that a user does not meet those assumptions and the result is an error message that is not exactly clear about what to do next.

For each ecosystem supported in the `lockfile_generator`, the pre-requisites for available tools and their versions should be confirmed. Helpful messages should be provided when the pre-requisites are not met.

## Additional Information

Here is an example of the experience when a Python `requirements.txt` manifest is used, but `pip-compile` is not installed and on the `PATH`:

```bash
~/dev/delme/manifest_test  2  1
❯ ~/dev/phylum/localdev/cli/target/debug/phylum --version
phylum v5.1.0-6-g0f1a16d

~/dev/delme/manifest_test  2  1
❯ l
total 8
drwxr-xr-x   5 maxrake  staff   160B May  5 17:56 .
drwxr-xr-x  25 maxrake  staff   800B May  5 13:59 ..
-rw-------   1 maxrake  staff   177B May  5 15:12 .phylum_project
drwxr-xr-x   3 maxrake  staff    96B May  5 15:35 pip
drwxr-xr-x   9 maxrake  staff   288B May  5 17:51 yarn

~/dev/delme/manifest_test  2  1
❯ cat .phylum_project
id: afb35f8b-bce5-41ce-82a1-dee88e1bf39d
name: manifest_test
created_at: 2023-05-05T14:01:30.038872-05:00
group_name: null
lockfiles:
- path: ./pip/requirements.txt
  type: pip

~/dev/delme/manifest_test  2  1
❯ l pip
total 8
drwxr-xr-x  3 maxrake  staff    96B May  5 15:35 .
drwxr-xr-x  5 maxrake  staff   160B May  5 17:56 ..
-rw-r--r--  1 maxrake  staff     8B May  5 13:59 requirements.txt

~/dev/delme/manifest_test  2  1
❯ cat pip/requirements.txt
pyyaml


~/dev/delme/manifest_test  2  1
❯ ~/dev/phylum/localdev/cli/target/debug/phylum parse
Generating lockfile for manifest "/Users/maxrake/dev/delme/manifest_test/./pip/requirements.txt" using Pip…
❗ Error: failed to run command "cd \"/Users/maxrake/dev/delme/manifest_test/pip\" && \"pip-compile\" \"-o\" \"requirements-locked.txt\" \"/Users/maxrake/dev/delme/manifest_test/./pip/requirements.txt\"": No such file or directory (os error 2)

~/dev/delme/manifest_test  2  1
❌ 1 ❯ which pip-compile
pip-compile not found

~/dev/delme/manifest_test  2  1
❌ 1 ❯ pipx install --python /Users/maxrake/.pyenv/shims/python3.11 pip-tools
  installed package pip-tools 6.13.0, installed using Python 3.11.3
  These apps are now globally available
    - pip-compile
    - pip-sync
done! ✨ 🌟 ✨

~/dev/delme/manifest_test  2  1
❯ ~/dev/phylum/localdev/cli/target/debug/phylum parse
Generating lockfile for manifest "/Users/maxrake/dev/delme/manifest_test/./pip/requirements.txt" using Pip…
[
  {
    "name": "pyyaml",
    "version": "6.0",
    "type": "pypi"
  }
]
```

The same thing is possible if a tool makes use of an option that is only available in newer/specific versions. For instance, `lockfile_generator::yarn::Yarn` makes use of an option that is not available in "classic yarn" (v1.x).

## Acceptance Criteria
- [ ] Tool expectations are checked for existence before use (#1096)
- [ ] Tool versions are checked for validity before use (#1097)
- [ ] Helpful messages are provided when the pre-requisites are not met (#1095)
- [ ] Documentation is updated

**Comment by cd-work** [comment]
> However, it is possible that a user does not meet those assumptions and the result is an error message that is not exactly clear about what to do next.

I don't see the full issue here tbh. To me it prints a very clear error about what it tried to do and why it didn't work. What is your issue with the error message exactly?

**Comment by maxrake** [comment]
> What is your issue with the error message exactly?

In the example provided, the error message was:

```
❗ Error: failed to run command "cd \"/Users/maxrake/dev/delme/manifest_test/pip\" && \"pip-compile\" \"-o\" \"requirements-locked.txt\" \"/Users/maxrake/dev/delme/manifest_test/./pip/requirements.txt\"": No such file or directory (os error 2)
```

With just that to go on, a user would be forgiven if they thought "No such file or directory (os error 2)" referred to `/Users/maxrake/dev/delme/manifest_test/./pip/requirements.txt`. How are they expected to know anything about the pre-requisite of having `pip-tools` installed so `pip-compile` is available? What if it is installed, but the wrong version? 

These are not just thought experiments. This issue was created because @furi0us333 experienced this exact problem and then @louislang confirmed the desire for better error messaging. Perhaps they have more detail to provide, for what makes a good UX. Here are two resources that may help:

* [CLI Guidelines: Errors](https://clig.dev/#errors)
* [12 Factor CLI Apps](https://medium.com/@jdxcode/12-factor-cli-apps-dd3c227a0e46)
  * See "5. Handle things going wrong"

**Comment by cd-work** [comment]
> How are they expected to know anything about the pre-requisite of having pip-tools installed so pip-compile is available?

It's both in the error message and in our documentation. If people don't read the error message or docs, I'm not sure there's much we can do?

> What if it is installed, but the wrong version?

Then it will be a different error?

I personally wasn't aware of how Rust outputs the working dir change in the debug output of the command. I'm fine with getting rid of the whole `cd` stuff.

**Comment by maxrake** [comment]
> It's both in the error message and in our documentation. If people don't read the error message or docs, I'm not sure there's much we can do?

`pip-tools` does not show up in either the error message or the documentation. This is the package that is required to be installed since it provides `pip-compile`. A Python developer using the Phylum CLI could easily have a manifest file covered by `pip-compile` _and also_ have no idea what `pip-compile` is or how to get it.

`pip-compile` shows up once in the documentation...on the [Analyzing Dependencies page](https://docs.phylum.io/docs/analyzing-dependencies). Granted, it shows up in the error message, but the error message does not guide the user in the right direction. From the [CLI Guidelines: Errors](https://clig.dev/#errors) section:

> Catch errors and [rewrite them for humans](https://www.nngroup.com/articles/error-message-guidelines/). If you’re expecting an error to happen, catch it and rewrite the error message to be useful. Think of it like a conversation, where the user has done something wrong and the program is guiding them in the right direction. Example: “Can’t write to file.txt. You might need to make it writable by running ‘chmod +w file.txt’.”

Following this advice, the error message is expected to happen when `pip-compile` is not available. That can be checked for by the CLI and then a message provided. Something like:

> `pip-compile` is required to convert the manifest at {manifest_file_path} to a lockfile. Please install the `pip-tools` Python package to make `pip-compile` available. Full documentation: https://pip-tools.readthedocs.io/en/latest/

**Comment by kylewillmon** [comment]
Most of the issues identified here are (or will be) addressed in the following issues:

- #1084
- #1085
- #1086

In particular, #1087 introduced an improved error message when a required tool is not found (or not accessible).

The rest of this issue seems to be about instructing the user of what to do when the tools fails (e.g., "You may need to install `pip-tools`"). But that gets complicated quickly...

**Comment by maxrake** [comment]
The acceptance criteria were spun off into separate issues:

* #1096 
* #1097 
* #1095 

That might mean this issue is more of a story now.

**Comment by kylewillmon** [comment]
Thanks! The smaller issues are much easier to reason about, discuss, and take action on. Closing this issue in favor of those.
